### ISSUE TITLE
This repository is over its data quota.

### ISSUE THREAD

**Issue by LinGeorge** [achen353/Face-Mask-Detector#1]
Hello, I try to "git lfs pull" the dataset stored on git large file storage system, but it seems that your repository is over its data quota. Is it possible to upload the dataset on the share drive and update the link on README? Please let me know if this method is feasible. Thanks!

**Comment by achen353** [comment]
Hi, @LinGeorge thanks for reach out. I've added the link to download the dataset to both versions of README.md.
